### ISSUE TITLE
Autoplay video

### ISSUE THREAD

**Issue by joshrives** [ryrych/rlightbox2#4]
Any ideas on autoplaying a youtube video when the lightbox opens? I tried just adding autoplay=1 to the youtube url but no luck there.

**Comment by ryrych** [comment]
It seems that I didn’t take this into account while parsing urls. I add this to my TODO for the next version.
Could you tell me, what other parameters would you like? Or should it up to a user to define them (leave a url as is)?

**Comment by joshrives** [comment]
I think leave the url as is would be fine. I'll be adding rel=0 to get rid of the related videos at the end, hd=1 to play HD video and autoplay=yes. The autoplay is the most important since you have to click twice to play a video (once to open lightbox and then once to play).

**Comment by ryrych** [comment]
fixed in testing
