### ISSUE TITLE
window Refresh (firefox)

### ISSUE THREAD

**Issue by cVasquez3** [ryrych/rlightbox2#5]
The Slider works beautifully. 

Now my issue is on the home page of my website i have a first play video and a link to click on to open the pop-out video (rlightbox).

In Safari and Chrome Browser there is no issues i can pause the first play video and select my link to activate the pop-out video. and the first play video no my website stays paused.

Now in Firefox...when going to my website the first play video starts, i pause the video...then select the link that activates the pop-out video(rlightbox) and it refreshes the whole page opening the popout video but also starting the first play video again.

is it possible to not have the whole window refresh in the Firefox browser?

thanks Chris

**Comment by ryrych** [comment]
Sorry, but I don’t quite follow you.
What is the ‘first video play’? Do you have a video that starts automatically? And then you pause it and click on a link to open rlightbox? Is it right?

Could you give me the link to your home page?

**Comment by cVasquez3** [comment]
Yes you have it correct.. I have a first play video on my website. Then I pause it to click one the link to open rlightbox .. I'll up load the web page on Monday and send you the link.. Thanks

**Comment by cVasquez3** [comment]
ok here is the link to the website....http://www.iuvideo.com/2012_iuSite/

so you know its works perfectly for Safari, Chrome and Internet explorer ..... just has that one issue with Firefox.

thanks

**Comment by ryrych** [comment]
OK, I'll take a look at it.

**Comment by ryrych** [comment]
For some reasons, the frame the first video is embed is refreshed. I think that a great workaround would be to call the first video programmatically when the page loads. You could for example embed it with oEmbed (Vimeo supports it).

Now I don’t have much time to test your issue in as many browsers as possible. But are you sure that only Firefox is affected?

Anyway you can watch this thread:
http://www.sitepoint.com/forums/showthread.php?825811-Firefox-

**Comment by cVasquez3** [comment]
yes sure its only firefox.

--- On Thu, 2/2/12, Wojciech Ryrych reply@reply.github.com wrote:

**Comment by cVasquez3** [comment]
ok So here is some New information.

first off the link to the page has changed to 

http://www.iuvideo.com/

Next i Took off the first play function from the vimeo and rlightbox worked if you never click the vimeo play button in the first place.

but if you go to the page press play  on the vimeo video and decide that your done watching it press pause and click on one of the bottom links below our same error occurs the video refreshes and plays again. 

Now i tryed the old oEmed code and it didnt work as hoped for our problem still occurred.

Saw the thread and tried it in chrome and it worked fine ...firefox seems to be the only browser.

and here is some food for thought.....on this page 
http://www.iuvideo.com/html/aboutUs.html
i put a quicktime video that just plays and looks...just a plug it...i didn't use vimeo and in firefox the video plays ontop of the rlightbox.

i know you dont have much time but if you could just forward this to your thread that would be great.
thanks

**Comment by ryrych** [comment]
1. If it is only Firefox and as you know, Firefox is very standards compliant browsers, I cannot help. I tried to talk about it in Mozilla’s IRC but none helped me. I’ll do my best to investigate it but can’t promise anything.
2. I think that this is a standard bug I overlooked. I will attend to it ASAP.

**Comment by ryrych** [comment]
One more request. Could you try the #1 with another lightbox like pretty photo?

**Comment by ryrych** [comment]
OK. As I supposed, #2 is a standard issue and it is up to you. Basically flash or other plug-ins are stacked on top of other layers. This may help:
http://thecssbug.com/flash-on-top-of-lightbox

**Comment by ryrych** [comment]
OK. Finally figured #1 out. It seems that setting ‘overflow: hidden’ to body tag cause frames to be refreshed in Firefox. I’ll release point release as soon as possible.

Thanks for reporting this bug!

**Comment by cVasquez3** [comment]
you asked..... Could you try the #1 with another lightbox like pretty photo?

i tried pretty photo and it worked fine.

**Comment by ryrych** [comment]
Does the new point release solve your problem? I hope so.

**Comment by cVasquez3** [comment]
Good stuff!!  Your a winner! Thanks it worked great.
