### ISSUE TITLE
Image case sensitivity

### ISSUE THREAD

**Issue by sheldond** [ryrych/rlightbox2#7]
rlightbox seems to be selecting images based on their file extension in a case sensitive manner, this means all images with the extension "JPG" are ignored by rlightbox while images with the extension "jpg" work.

Images with the extension "jpeg" are also ignored by rlightbox.

Thanks!

**Comment by ryrych** [comment]
Thanks, it will be fixed in the new version.

**Comment by ryrych** [comment]
Fixed in testing
