### ISSUE TITLE
Returning to an image hangs browser in IE8

### ISSUE THREAD

**Issue by astockwell** [ryrych/rlightbox2#9]
Hi there, first off great script!  Only problem I've noticed is during x-browser testing in IE8 (this is repeatable on your [demo page](http://ryrych.github.com/rlightbox2/) in IE8, on Win XP or 7): 

If you click on an image and either close the lightbox or click next/prev, then return to the same image again (click it again or next/prev back to it), the lightbox will hang up the browser and you can't do anything else. It doesn't appear to get far enough to load the content you were looking for, even though that content obviously can be found and is already cached.

I've been at it for a few hours trying to fix (client wants compatibility), and have tried the following to no avail: 
1) Set doctype to HTML5, XHTML (trans 1.0 and basic 1.1), and HTML 4.01 trans
2) Reset all paths (that I could find) in CSS files to absolute paths, per [this forum](http://www.qa.downappz.com/questions/fancybox-hanging-in-ie.html)
3) Removed my custom scripting for fear of interfering with your code
4) Changed the meta http-equiv="X-UA-Compatible" content="IE=7" to all manner of 7,8,edge,etc

Since I can replicate the issue on your demo page, I don't believe it's specific to my environment, however, I'm using this with Wordpress 3.3.1 and jQuery 1.7.1. 

**Note:** It works fine enough in IE7, the problem is in IE8 only.

Would LOVE to have a fix for this, wondering if it's possibly an issue with the queue system or error handling with image/asset urls?

P.S. It'd take me a million years to write a script like this, so no pretentious tone here!

**Comment by ryrych** [comment]
Hi,

so the steps to reproduce are:
• click on an image in a set (gallery), any image: first, last, in the middle?
• the browser freezes

I’ll look at it ASAP.

**Comment by astockwell** [comment]
Right, any image, but the key is you must open the image **twice** in the same session, e.g. click the n-th image to open in lightbox, click 'next image' to n+1, the click 'prev' to return to the n-th. Freezes and the bounding box defaults to appx 300x300, CPU use goes to 100%, almost like an infinite loop. Thanks for your help!!

**Comment by ryrych** [comment]
I’m sorry. I would like to help, but now I don’t have access to Windows/IE. But I’m sure that the problem relates to image caching and the snippet I borrowed from https://github.com/desandro/imagesloaded

Were you testing in IE/compatibility mode or native IE8?

**Comment by astockwell** [comment]
You may well be right, at quick glance some of their issues read similarly to this. Will look into more tomorrow. If you're interested and have the time available to test a bit, we can probably set you up with a virtual test server instance w/ IE if it will expedite things. Email me if you're interested and I'll send you the info.

**Comment by astockwell** [comment]
Hi, sorry for the hiatus.  

Definitely has to do with that code and the browser caching the images. Replacing line #s 864/865 with:

```
var BLANK = (!$.browser.msie) ? 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==' : window.location.href+'#';                        
this.src = BLANK;                         
this.src = src; 
```

fixes IE8 tripping on itself (I know $.browser is a hack, but it works for the moment, can clean it later). However, now whenever you return to an image that's been cached by the browser, it somehow skips out of the resize/scale logic and snaps to the image's full native size, horiz and vertically centered. Without reverse engineering the whole bit, any ideas where in the code there could be a conditional call (again w/ .browser) placed to kick off the resize events? That seems to be the quickest/easiest fix, but if you have other ideas, let me know.

**Comment by ryrych** [comment]
Hi,

Unfortunately I think that $.browser will be deprecated soon. But as a temporary solution,it’s OK.
The previous version did not use this snippet, and I didn’t cache images by applying date string (milliseconds) to a URL. Thus each image (even the same) was unique (unique URL).
Have a peek: https://github.com/ryrych/rlightbox2/blob/v1.0.1/widget/lib/jquery.ui.rlightbox.js (line 750)

I would like to ask you to discuss this issue upstream so that others could benefit from it.

Know that now I don’t feel like working on rlightbox. I lost interest in it. It was one of my first projects and it’s time to move on. So I don’t know if there will be another version.

**Comment by astockwell** [comment]
Indeed, reversing commit a58a3b41495a5749143b8b1c9df2be6cc53e0684 did the trick (albeit without caching). I appreciate your honesty about where your attention lies, but since I'm fairly new to the github universe I'm not 100% sure what you mean by discussing upstream? 

Either way this should help others who stumble here with the problem. I may keep playing with it or look for another means besides $.broswer to conditionally handle IE. Thanks again.

**Comment by ryrych** [comment]
Upstream is a generic term when you have a project with some dependencies. If there is a bug in your project and the bug is related to one of those dependencies, you should not fill a bug report in the project’s bug tracker, but where it occurs, that is upstream (= up the stream). :)

So I encourage you to open a ticket with this bug in Desandro’s imageloaded, ok? :) That way more people could benefit from it.

regards
